apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    tekton.dev/git-0: github.com
type: kubernetes.io/basic-auth
stringData:
  username: <REPLACE>
  password: <REPLACE>